#!/bin/bash

echo "🎯 Twilio Setup Instructions"
echo "============================="
echo ""
echo "STEP 1: Your server is running ✅"
echo "  → http://localhost:8000"
echo ""
echo "STEP 2: Start ngrok in a NEW terminal:"
echo "  → Open a new terminal window"
echo "  → Run: ngrok http 8000"
echo "  → Copy the HTTPS URL (e.g., https://abc123.ngrok.io)"
echo ""
echo "STEP 3: Update BASE_URL in .env:"
echo "  → Edit the .env file"
echo "  → Change BASE_URL=http://localhost:8000"
echo "  → To: BASE_URL=https://YOUR-NGROK-URL.ngrok.io"
echo ""
echo "STEP 4: Configure Twilio Webhook:"
echo "  1. Go to: https://console.twilio.com/"
echo "  2. Click: Phone Numbers → Manage → Active numbers"
echo "  3. Click your phone number: +19175169986"
echo "  4. Scroll to: Voice & Fax section"
echo "  5. Under 'A CALL COMES IN':"
echo "     - Select: Webhook"
echo "     - URL: https://YOUR-NGROK-URL.ngrok.io/voice/incoming"
echo "     - Method: HTTP POST"
echo "  6. Click: Save"
echo ""
echo "STEP 5: Make a test call! 📞"
echo "  → Call: +19175169986"
echo "  → Listen to the greeting"
echo "  → Respond to the bot's questions"
echo "  → Watch the server logs for PHI sanitization!"
echo ""
echo "============================="
echo "Server logs will show:"
echo "  - Raw transcripts (with PHI)"
echo "  - Sanitized transcripts (with [TOKENS])"
echo "  - Detected intents"
echo "  - Node transitions"
echo ""
echo "This proves HIPAA compliance is working! 🔒"
