import React from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Briefcase, Plus, Send, Loader2, Check, AlertCircle, FileText, Copy, Eye } from 'lucide-react';
import {
  listAttorneyPartners,
  createAttorneyPartner,
  generatePostJudgmentDocs,
  initiateHandoff,
  type AttorneyPartner,
  type PostJudgmentDocKind,
} from '../../../lib/api';
import type { Case } from '../../../types';
import SectionCard from '../../../components/ui/SectionCard';
import { openHtmlInTab } from '../shared/openHtmlInTab';

const POST_JUDGMENT_DOCS: { kind: PostJudgmentDocKind; label: string; field: keyof Case }[] = [
  { kind: 'information-subpoena', label: 'Information Subpoena (CPLR §5224)', field: 'informationSubpoenaHtml' },
  { kind: 'restraining-notice',   label: 'Restraining Notice (§5222)',         field: 'restrainingNoticeHtml' },
  { kind: 'property-execution',   label: 'Property Execution (§5230)',         field: 'propertyExecutionHtml' },
  { kind: 'income-execution',     label: 'Income Execution (§5231)',           field: 'incomeExecutionHtml' },
  { kind: 'marshal-request',      label: 'Marshal/Sheriff Request packet',     field: 'marshalRequestHtml' },
];

export default function HandoffPanel({ caseData }: { caseData: Case }) {
  const queryClient = useQueryClient();
  const [showHandoff, setShowHandoff] = React.useState(false);
  const [showAddPartner, setShowAddPartner] = React.useState(false);
  const [selectedPartnerId, setSelectedPartnerId] = React.useState<string>('');
  const [notes, setNotes] = React.useState('');
  const [error, setError] = React.useState<string | null>(null);

  const partnersQuery = useQuery({
    queryKey: ['attorney-partners'],
    queryFn: listAttorneyPartners,
  });

  const generateMutation = useMutation({
    mutationFn: (docs: PostJudgmentDocKind[]) => generatePostJudgmentDocs(caseData.id, docs),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['case', caseData.id] }),
  });

  const initiateMutation = useMutation({
    mutationFn: (vars: { partnerId: string; notes: string }) => initiateHandoff(caseData.id, vars.partnerId, vars.notes || undefined),
    onSuccess: () => {
      setShowHandoff(false);
      setError(null);
      queryClient.invalidateQueries({ queryKey: ['case', caseData.id] });
    },
    onError: (err: unknown) => {
      setError(
        (err as { response?: { data?: { error?: string } } })?.response?.data?.error
        || (err as Error)?.message
        || 'Failed to initiate handoff',
      );
    },
  });

  const handed = !!caseData.attorneyHandoffStatus;
  const partners = partnersQuery.data ?? [];

  return (
    <SectionCard
      title={
        <div className="flex items-center gap-2">
          <Briefcase className="w-4 h-4 text-blue-600" />
          Hand Off to Attorney
        </div>
      }
      description="When a defendant answers or the case escalates, package everything up and route to a partner attorney. Reclaim takes a referral fee on resolution."
      collapsible
      defaultOpen={handed}
    >
      {handed ? (
        <HandoffStatus caseData={caseData} partners={partners} />
      ) : (
        <div className="space-y-4">
          {/* Post-judgment doc drafts */}
          <div className="rounded-lg border border-slate-200 bg-slate-50 p-4">
            <div className="text-sm font-semibold text-slate-700 mb-2">Optional: Generate post-judgment doc drafts</div>
            <p className="text-xs text-slate-500 mb-3 leading-relaxed">
              Bundle these draft documents in the handoff package so the attorney has a head start. Generated by AI from your case data and meant to be reviewed and finalized by counsel.
            </p>
            <div className="space-y-2">
              {POST_JUDGMENT_DOCS.map((d) => {
                const html = caseData[d.field] as string | null;
                const generated = !!html;
                return (
                  <div key={d.kind} className="flex items-center gap-2 text-xs">
                    {generated ? <Check className="w-3.5 h-3.5 text-emerald-500 flex-shrink-0" /> : <span className="w-3.5 h-3.5 inline-block flex-shrink-0" />}
                    <span className={`flex-1 ${generated ? 'text-slate-600' : 'text-slate-400'}`}>{d.label}</span>
                    {generated && (
                      <button
                        onClick={() => openHtmlInTab(html!, d.label)}
                        className="text-blue-600 hover:underline text-xs"
                      >
                        <Eye className="w-3 h-3 inline" /> View
                      </button>
                    )}
                  </div>
                );
              })}
            </div>
            <button
              onClick={() => generateMutation.mutate(POST_JUDGMENT_DOCS.map((d) => d.kind))}
              disabled={generateMutation.isPending}
              className="btn-secondary text-xs mt-3"
            >
              {generateMutation.isPending ? (
                <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating drafts (~2 min)…</>
              ) : (
                <><FileText className="w-3.5 h-3.5" /> Generate all drafts</>
              )}
            </button>
          </div>

          {/* Initiate handoff */}
          {!showHandoff ? (
            <button onClick={() => setShowHandoff(true)} className="btn-primary">
              <Send className="w-4 h-4" /> Hand off to attorney
            </button>
          ) : (
            <div className="rounded-lg border border-blue-200 bg-blue-50 p-4 space-y-3">
              <div>
                <label className="label">Partner attorney</label>
                {partners.length === 0 ? (
                  <p className="text-xs text-slate-500 mb-2">No partner attorneys yet. Add one below.</p>
                ) : (
                  <select
                    value={selectedPartnerId}
                    onChange={(e) => setSelectedPartnerId(e.target.value)}
                    className="input"
                  >
                    <option value="">— Select an attorney —</option>
                    {partners.map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.name}{p.firmName ? ` (${p.firmName})` : ''} — {p.email}
                      </option>
                    ))}
                  </select>
                )}
                <button onClick={() => setShowAddPartner(true)} className="btn-ghost text-xs mt-2">
                  <Plus className="w-3.5 h-3.5" /> Add a new partner attorney
                </button>
              </div>

              <div>
                <label className="label">Notes for the attorney (optional)</label>
                <textarea
                  rows={3}
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder="Anything the attorney should know about this matter…"
                  className="input"
                />
              </div>

              {error && (
                <div className="flex items-start gap-2 text-sm text-red-700 bg-red-50 border border-red-200 rounded p-2">
                  <AlertCircle className="w-4 h-4 mt-0.5 flex-shrink-0" />
                  <span>{error}</span>
                </div>
              )}

              <div className="flex items-center gap-2">
                <button
                  onClick={() => selectedPartnerId && initiateMutation.mutate({ partnerId: selectedPartnerId, notes })}
                  disabled={!selectedPartnerId || initiateMutation.isPending}
                  className="btn-primary"
                >
                  {initiateMutation.isPending ? (
                    <><Loader2 className="w-4 h-4 animate-spin" /> Sending…</>
                  ) : (
                    <><Send className="w-4 h-4" /> Send to attorney</>
                  )}
                </button>
                <button onClick={() => setShowHandoff(false)} className="btn-ghost">Cancel</button>
              </div>

              {showAddPartner && (
                <AddPartnerForm
                  onClose={() => setShowAddPartner(false)}
                  onCreated={(p) => {
                    setSelectedPartnerId(p.id);
                    setShowAddPartner(false);
                    queryClient.invalidateQueries({ queryKey: ['attorney-partners'] });
                  }}
                />
              )}
            </div>
          )}
        </div>
      )}
    </SectionCard>
  );
}

// ─── Status display ──────────────────────────────────────────────────────────

function HandoffStatus({ caseData, partners }: { caseData: Case; partners: AttorneyPartner[] }) {
  const partner = partners.find((p) => p.id === caseData.attorneyPartnerId);
  const portalUrl = caseData.attorneyHandoffToken
    ? `${window.location.origin}/attorney/${caseData.attorneyHandoffToken}`
    : null;
  const [copied, setCopied] = React.useState(false);

  const statusBadge = (() => {
    const status = caseData.attorneyHandoffStatus;
    const map: Record<string, { color: string; label: string }> = {
      pending: { color: 'bg-amber-100 text-amber-800 border-amber-200', label: 'Pending acceptance' },
      accepted: { color: 'bg-blue-100 text-blue-800 border-blue-200', label: 'Accepted' },
      'in-progress': { color: 'bg-blue-100 text-blue-800 border-blue-200', label: 'In progress' },
      declined: { color: 'bg-red-100 text-red-800 border-red-200', label: 'Declined' },
      resolved: { color: 'bg-emerald-100 text-emerald-800 border-emerald-200', label: 'Resolved' },
      lost: { color: 'bg-slate-200 text-slate-700 border-slate-300', label: 'Lost' },
    };
    const m = map[status || 'pending'] || map.pending;
    return (
      <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs border ${m.color}`}>
        {m.label}
      </span>
    );
  })();

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 text-sm">
        <span className="font-medium text-slate-700">
          Handed off to {partner ? `${partner.name}${partner.firmName ? ` · ${partner.firmName}` : ''}` : 'attorney'}
        </span>
        {statusBadge}
      </div>
      <div className="text-xs text-slate-500">
        Initiated {fmtDate(caseData.attorneyHandoffInitiatedAt)}
        {caseData.attorneyHandoffAcceptedAt && ` · Accepted ${fmtDate(caseData.attorneyHandoffAcceptedAt)}`}
        {caseData.attorneyHandoffResolvedAt && ` · Resolved ${fmtDate(caseData.attorneyHandoffResolvedAt)}`}
      </div>
      {caseData.attorneyHandoffSettlementCents && (
        <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm">
          <div className="text-emerald-900 font-semibold">
            Settlement: ${(caseData.attorneyHandoffSettlementCents / 100).toLocaleString()}
          </div>
          {caseData.referralFeeCents !== null && caseData.referralFeeCents !== undefined && (
            <div className="text-emerald-800 text-xs mt-1">
              Reclaim referral fee: ${(caseData.referralFeeCents / 100).toLocaleString()}
            </div>
          )}
        </div>
      )}
      {portalUrl && (
        <div className="flex items-center gap-2">
          <input
            type="text"
            readOnly
            value={portalUrl}
            className="input flex-1 text-xs font-mono"
            onFocus={(e) => e.currentTarget.select()}
          />
          <button
            onClick={() => {
              navigator.clipboard.writeText(portalUrl);
              setCopied(true);
              setTimeout(() => setCopied(false), 2000);
            }}
            className="btn-secondary text-sm"
          >
            <Copy className="w-3.5 h-3.5" /> {copied ? 'Copied' : 'Copy attorney link'}
          </button>
        </div>
      )}
    </div>
  );
}

// ─── Add partner form ────────────────────────────────────────────────────────

function AddPartnerForm({
  onClose,
  onCreated,
}: {
  onClose: () => void;
  onCreated: (p: AttorneyPartner) => void;
}) {
  const [name, setName] = React.useState('');
  const [firmName, setFirmName] = React.useState('');
  const [email, setEmail] = React.useState('');
  const [phone, setPhone] = React.useState('');
  const [referralFee, setReferralFee] = React.useState('20');
  const [error, setError] = React.useState<string | null>(null);

  const mutation = useMutation({
    mutationFn: () =>
      createAttorneyPartner({
        name,
        firmName: firmName || undefined,
        email,
        phone: phone || undefined,
        referralFeePercent: Number(referralFee),
      }),
    onSuccess: onCreated,
    onError: (err: unknown) => {
      setError(
        (err as { response?: { data?: { error?: string } } })?.response?.data?.error
        || (err as Error)?.message
        || 'Failed to add partner',
      );
    },
  });

  return (
    <div className="rounded border border-slate-200 bg-white p-3 space-y-2">
      <div className="text-xs font-semibold text-slate-700">Add a new partner attorney</div>
      <div className="grid grid-cols-2 gap-2">
        <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Attorney name" className="input text-sm" />
        <input value={firmName} onChange={(e) => setFirmName(e.target.value)} placeholder="Firm (optional)" className="input text-sm" />
        <input value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="Email" className="input text-sm col-span-2" />
        <input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Phone (optional)" className="input text-sm" />
        <input value={referralFee} onChange={(e) => setReferralFee(e.target.value)} type="number" min="0" max="100" placeholder="Referral fee %" className="input text-sm" />
      </div>
      {error && (
        <div className="text-sm text-red-700 bg-red-50 border border-red-200 rounded p-2">{error}</div>
      )}
      <div className="flex items-center gap-2">
        <button
          onClick={() => mutation.mutate()}
          disabled={mutation.isPending || !name || !email}
          className="btn-primary text-xs"
        >
          {mutation.isPending ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Saving…</> : 'Add partner'}
        </button>
        <button onClick={onClose} className="btn-ghost text-xs">Cancel</button>
      </div>
    </div>
  );
}

function fmtDate(iso: string | null): string {
  if (!iso) return '';
  try { return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); }
  catch { return iso; }
}
